<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ajouter votre tâches à faire</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="css/add.css">
</head>
<!-- Tout les endroit ou on peut ajouter les informations de chaque taches
 avec le boutons pour envoyer  -->
<body>
    <form action="index.php?action=create" method="post">
    <?php if(isset($erreur)): ?>
                <p class="errorMessage"><?=$erreur?></p>
            <?php endif; ?>
            <input filter_var(FILTER_SANITIZE_NUMBER_INT)  class="input-group-text" type="text" name="task_nom" placeholder="Nom de tâches">
            <input id="dateid" class="input-group-text" type="date" name="task_date" placeholder="Date Limite" >
            <input class="input-group-text" type="text" name="task_categorie" placeholder="Catégorie">
            <button class="btn btn-primary" type="submit" >Ajouter à la liste</button>
    </form>
</body>
</html>